default: &default
  adapter: mysql2
  username: root
  password:
  host: localhost
  pool: 5
  timeout: 5000
  
production:
  <<: *default
  database: forum_productio
  
development:
  <<: *default
  database: forum_development
  
test: &test
  <<: *default
  database: forum_test
  
cucumber:
  <<: *test